alpa = _{SOI ~ program ~ EOI }

program = { expr* }

expr = { number | symbol | sexpr | qexpr }

sexpr = { "(" ~ expr* ~ ")"}

qexpr = { "'(" ~ expr* ~ ")"}

symbol = { number_op | qexpr_op }
  number_op = { add | subtract | multiply | divide }
    add      = { "+" }
    subtract = { "-" }
    multiply = { "*" }
    divide   = { "/" }
  qexpr_op = { first | rest }
    first = { "पहिलो" }
    rest = { "बाँकी" }

number = @{ ( "+" | "-" )? ~ '०'..'९'+ }


WHITESPACE = _{ " " | "\t" }